## Comantario dummy
---
- hosts: localhost
  connection: local

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: DemoRG3
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: DemoRG3
      name: DemovNet3
      address_prefixes: "192.168.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: DemoRG3
      name: DemoSubnet3
      address_prefix: "192.168.3.0/24"
      virtual_network: DemovNet3 

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: DemoRG3
      allocation_method: Static
      name: LinuxPublicIP

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: DemoRG3
      name: LinuxNSG
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: DemoRG3
      name: LinuxNIC
      virtual_network: DemovNet3
      subnet: DemoSubnet3
      public_ip_name: LinuxPublicIP
      security_group: LinuxNSG

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: DemoRG3
      name: UbuntuServer01
      vm_size: Standard_DS1_v2
      admin_username: labadmin
      admin_password: Acero2018
      network_interfaces: LinuxNIC
      os_type: Linux
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04.0-LTS
        version: latest