---
- hosts: localhost
  connection: local

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: {{ResGroup}}
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: {{ResGroup}}
      name: DemovNet
      address_prefixes: "192.168.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: {{ResGroup}}
      name: DemoSubnet
      address_prefix: "192.168.3.0/24"
      virtual_network: DemovNet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: {{ResGroup}}
      allocation_method: Dynamic
      name: DemoPublicIP
      register: output_ip_address

  - name: Output public IP
    debug:
      msg: "Public IP is {{output_ip_address.state.ip_address}}"

  - name: Create Network Security Group that allows RDP
    azure_rm_securitygroup:
      resource_group: {{ResGroup}}
      name: DemoNSG
      rules:
        - name: Allow_RemoteDesktop
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound

        - name: Allow_WinRM
          protocol: Tcp
          destination_port_range: 5986
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: {{ResGroup}}
      name: DemoNIC
      virtual_network: DemovNet
      subnet: DemoSubnet
      public_ip_name: DemoPublicIP
      security_group: DemoNSG

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: {{ResGroup}}
      name: webServer03
      vm_size: Standard_DS1_v2
      admin_username: labadmin
      admin_password: {{adminpass}}
      network_interfaces: DemoNIC
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest