---
- hosts: localhost
  connection: local

  tasks:
  - name: Creating resource group
    azure_rm_resourcegroup:
      name: "{{ResGroup}}"
      location: eastus

  - name: Creating virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ResGroup}}"
      name: DemovNet
      address_prefixes: "192.168.0.0/16"

  - name: Adding subnet
    azure_rm_subnet:
      resource_group: "{{ResGroup}}"
      name: DemoSubnet
      address_prefix: "192.168.3.0/24"
      virtual_network: DemovNet

  - name: Creating public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ResGroup}}"
      allocation_method: Static
      name: "{{MachineName}}_PublicIP"
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "Public IP is {{output_ip_address.state.ip_address}}"
#      serverpublicipaddress: "{{output_ip_address.state.ip_address}}"

  - name: Creating Network Security Group that allows RDP and WinRM
    azure_rm_securitygroup:
      resource_group: "{{ResGroup}}"
      name: "{{MachineName}}_NSG"
      rules:
        - name: Allow_RemoteDesktop
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound

        - name: Allow_WinRM
          protocol: Tcp
          destination_port_range: 5986
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Creating virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ResGroup}}"
      name: "{{MachineName}}_NIC"
      virtual_network: DemovNet
      subnet: DemoSubnet
      public_ip_name: "{{MachineName}}_PublicIP"
      security_group: "{{MachineName}}_NSG"

  - name: Creating Windows VM
    azure_rm_virtualmachine:
      resource_group: "{{ResGroup}}"
      name: "{{MachineName}}"
      vm_size: Standard_DS1_v2
      admin_username: labadmin
      admin_password: "{{AdminPassword}}"
      network_interfaces: "{{MachineName}}_NIC"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest