---
- hosts: localhost
  connection: local

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: DemoRG3
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: DemoRG3
      name: DemovNet3
      address_prefixes: "192.168.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: DemoRG3
      name: DemoSubnet3
      address_prefix: "192.168.3.0/24"
      virtual_network: DemovNet3 

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: DemoRG3
      allocation_method: Static
      name: DemoPublicIP3

  - name: Create Network Security Group that allows RDP
    azure_rm_securitygroup:
      resource_group: DemoRG3
      name: DemoNSG3
      rules:
        - name: RemoteDesktop
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: DemoRG3
      name: DemoNIC3
      virtual_network: DemovNet3
      subnet: DemoSubnet3
      public_ip_name: DemoPublicIP3
      security_group: DemoNSG3

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: DemoRG3
      name: webServer03
      vm_size: Standard_DS1_v2
      admin_username: labadmin
      admin_password: Acero2018
      network_interfaces: DemoNIC3
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest