#deployWindowsAzureVirtualMachine.yaml
---
- hosts: localhost
  connection: local

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: DemoRG
        location: eastus
