---
- hosts: localhost
  connection: local

  tasks:

    - name: Create Linux DNS record on DNS Server
      win_dns_record:
        name: "myLinux"
        type: "A"
        value: "192.168.3.10"
        zone: "testing.cl"
    - name: Create PTR record
      win_dns_record:
        name: "10"
        type: "PTR"
        value: "myLinux"
        zone: "3.168.192.in-addr.arpa"


#    win_shell: Add-DnsServerResourceRecordA -Name "mylinux" -ZoneName "testing.cl" -AllowUpdateAny -IPv4Address "192.168.3.10" -TimeToLive 01:00:00 -CreatePtr
